import { Donor, SeekerRequest, RelayChannel } from '@/types';

export const INITIAL_HOSPITALS = [
  {
    id: 'hosp-1',
    name: 'Apollo Emergency Trauma & Critical Care',
    address: 'Sector 26, Main Expressway, South Medical District',
    lat: 28.5672,
    lng: 77.2100,
    emergencyPhoneMasked: '+91 11-•••-108',
  },
  {
    id: 'hosp-2',
    name: 'Metro Life Line Hospital & Blood Bank',
    address: 'Ring Road Junction, Central City Wing',
    lat: 28.5921,
    lng: 77.2312,
    emergencyPhoneMasked: '+91 11-•••-911',
  },
  {
    id: 'hosp-3',
    name: 'City Memorial Surgical Institute',
    address: 'Avenue 4, West Campus Boulevard',
    lat: 28.5350,
    lng: 77.2580,
    emergencyPhoneMasked: '+91 11-•••-444',
  },
  {
    id: 'hosp-4',
    name: 'St. Jude Transfusion & Trauma Wing',
    address: 'Civic Plaza, North Healthcare Hub',
    lat: 28.6140,
    lng: 77.1950,
    emergencyPhoneMasked: '+91 11-•••-777',
  },
];

export const INITIAL_DONORS: Donor[] = [
  {
    id: 'donor-1',
    maskedCode: 'DX-4821',
    name: 'Alex R. (You)',
    phoneMasked: '+91 98••• ••210',
    bloodType: 'O-',
    status: 'AVAILABLE',
    city: 'New Delhi',
    pincode: '110029',
    lat: 28.5710,
    lng: 77.2150,
    responseRate: 99,
    avgResponseTimeMins: 3,
    totalDonations: 18,
    lastDonationDate: null,
    cooldownUntil: null,
    isEligible: true,
  },
  {
    id: 'donor-2',
    maskedCode: 'DX-7712',
    name: 'Priya M.',
    phoneMasked: '+91 97••• ••543',
    bloodType: 'B+',
    status: 'AVAILABLE',
    city: 'New Delhi',
    pincode: '110024',
    lat: 28.5620,
    lng: 77.2280,
    responseRate: 96,
    avgResponseTimeMins: 5,
    totalDonations: 8,
    lastDonationDate: null,
    cooldownUntil: null,
    isEligible: true,
  },
  {
    id: 'donor-3',
    maskedCode: 'DX-3329',
    name: 'Carlos S.',
    phoneMasked: '+91 91••• ••891',
    bloodType: 'A+',
    status: 'STANDBY',
    city: 'New Delhi',
    pincode: '110049',
    lat: 28.5580,
    lng: 77.2020,
    responseRate: 92,
    avgResponseTimeMins: 7,
    totalDonations: 12,
    lastDonationDate: null,
    cooldownUntil: null,
    isEligible: true,
  },
  {
    id: 'donor-4',
    maskedCode: 'DX-9182',
    name: 'Aisha K.',
    phoneMasked: '+91 99••• ••119',
    bloodType: 'O+',
    status: 'AVAILABLE',
    city: 'New Delhi',
    pincode: '110016',
    lat: 28.5490,
    lng: 77.2050,
    responseRate: 97,
    avgResponseTimeMins: 4,
    totalDonations: 14,
    lastDonationDate: null,
    cooldownUntil: null,
    isEligible: true,
  },
  {
    id: 'donor-5',
    maskedCode: 'DX-1049',
    name: 'Liam C.',
    phoneMasked: '+91 94••• ••784',
    bloodType: 'AB-',
    status: 'AVAILABLE',
    city: 'New Delhi',
    pincode: '110003',
    lat: 28.5850,
    lng: 77.2250,
    responseRate: 91,
    avgResponseTimeMins: 8,
    totalDonations: 5,
    lastDonationDate: null,
    cooldownUntil: null,
    isEligible: true,
  },
  {
    id: 'donor-6',
    maskedCode: 'DX-6321',
    name: 'Maya V.',
    phoneMasked: '+91 96••• ••402',
    bloodType: 'A-',
    status: 'AVAILABLE',
    city: 'New Delhi',
    pincode: '110017',
    lat: 28.5380,
    lng: 77.2180,
    responseRate: 94,
    avgResponseTimeMins: 6,
    totalDonations: 9,
    lastDonationDate: null,
    cooldownUntil: null,
    isEligible: true,
  },
  {
    id: 'donor-7',
    maskedCode: 'DX-5510',
    name: 'David T.',
    phoneMasked: '+91 93••• ••938',
    bloodType: 'B-',
    status: 'STANDBY',
    city: 'New Delhi',
    pincode: '110020',
    lat: 28.5300,
    lng: 77.2620,
    responseRate: 89,
    avgResponseTimeMins: 9,
    totalDonations: 4,
    lastDonationDate: null,
    cooldownUntil: null,
    isEligible: true,
  },
  {
    id: 'donor-8',
    maskedCode: 'DX-8240',
    name: 'Sofia N.',
    phoneMasked: '+91 98••• ••365',
    bloodType: 'AB+',
    status: 'AVAILABLE',
    city: 'New Delhi',
    pincode: '110001',
    lat: 28.6250,
    lng: 77.2150,
    responseRate: 98,
    avgResponseTimeMins: 4,
    totalDonations: 11,
    lastDonationDate: null,
    cooldownUntil: null,
    isEligible: true,
  },
  {
    id: 'donor-9',
    maskedCode: 'DX-2210',
    name: 'Jordan E. (In Cooldown)',
    phoneMasked: '+91 95••• ••671',
    bloodType: 'O-',
    status: 'RECENTLY_DONATED',
    city: 'New Delhi',
    pincode: '110019',
    lat: 28.5440,
    lng: 77.2510,
    responseRate: 95,
    avgResponseTimeMins: 5,
    totalDonations: 7,
    // Donated 20 days ago -> 70 days remaining in cooldown
    lastDonationDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    cooldownUntil: new Date(Date.now() + 70 * 24 * 60 * 60 * 1000).toISOString(),
    isEligible: false,
  },
];

export const INITIAL_REQUESTS: SeekerRequest[] = [
  {
    id: 'req-101',
    patientName: 'Rohan Sharma',
    patientId: 'PT-99482',
    recipientBloodType: 'B+',
    hospitalName: 'Apollo Emergency Trauma & Critical Care',
    hospitalAddress: 'Sector 26, Main Expressway, South Medical District',
    hospitalLat: 28.5672,
    hospitalLng: 77.2100,
    urgency: 'IMMEDIATE',
    unitsRequired: 2,
    prescriptionVerified: true,
    prescriptionFileName: 'Emergency_Trauma_Prescription_B_Pos.pdf',
    status: 'DISPATCHED',
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(), // 25 mins ago
    contactName: 'Dr. V. Malhotra (ICU Lead)',
    contactMaskedPhone: '+91 11-•••-108-EXT',
    dispatchedDonorIds: ['donor-1', 'donor-2', 'donor-4'],
  },
  {
    id: 'req-102',
    patientName: 'Sneha Patel',
    patientId: 'PT-41029',
    recipientBloodType: 'O-',
    hospitalName: 'Metro Life Line Hospital & Blood Bank',
    hospitalAddress: 'Ring Road Junction, Central City Wing',
    hospitalLat: 28.5921,
    hospitalLng: 77.2312,
    urgency: 'WITHIN_12_HOURS',
    unitsRequired: 1,
    prescriptionVerified: true,
    prescriptionFileName: 'Surgical_Preparedness_O_Neg.pdf',
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    contactName: 'Hospital Blood Desk',
    contactMaskedPhone: '+91 11-•••-911-EXT',
    dispatchedDonorIds: ['donor-1'],
  },
];

export const INITIAL_RELAY_CHANNELS: RelayChannel[] = [
  {
    id: 'relay-chan-101',
    requestId: 'req-101',
    seekerContactMasked: 'Dr. V. Malhotra (Apollo ICU)',
    donorId: 'donor-1',
    donorMaskedCode: 'DX-4821',
    virtualProxyNumber: '+91 800-RELAY-108-99',
    expiresAt: new Date(Date.now() + 23 * 60 * 60 * 1000).toISOString(), // ~23 hrs left
    status: 'ACTIVE',
    hospitalName: 'Apollo Emergency Trauma & Critical Care',
    bloodType: 'B+',
    unitsRequired: 2,
    messages: [
      {
        id: 'msg-1',
        sender: 'SYSTEM',
        senderMaskedName: 'BloodPulse Secure Relay',
        text: 'Encrypted relay bridge created. Both seeker and donor direct numbers are masked. Valid for 24 hours.',
        timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-2',
        sender: 'SEEKER',
        senderMaskedName: 'Apollo ICU Lead',
        text: 'Thank you for accepting! Patient Rohan Sharma is in Emergency OT 3. Blood bank counter #2 is ready for direct whole blood crossmatch.',
        timestamp: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-3',
        sender: 'DONOR',
        senderMaskedName: 'Donor DX-4821',
        text: 'Understood. I am 1.8 km away and arriving by cab in approximately 6 minutes. Have security know DX-4821 is coming for Emergency OT 3.',
        timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-4',
        sender: 'SEEKER',
        senderMaskedName: 'Apollo ICU Lead',
        text: 'Security gate passes confirmed under token DX-4821. Priority parking reserved at Emergency Entrance B.',
        timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
      },
    ],
  },
];
